// src/pages/index.tsx
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import CharacterForm from "~/components/CharacterForm";
import StoryFormatter from "~/components/StoryFormatter";
import ClipLoader from "react-spinners/ClipLoader";

type Response = {
  story: string;
  fighter1Name: string;
  fighter2Name: string;
};

const Home: NextPage = () => {
  const [response, setResponse] = useState<Response | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null); // Add this line

  return (
    <>
      <Head>
        <title>AI Fight Pits</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex max-w-full flex-col items-center justify-center gap-12 px-4 py-16 sm:max-w-2xl ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            AI <span className="text-[hsl(280,100%,70%)]">Fight</span> Pits
          </h1>
          <div className="flex max-w-2xl flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
            <h3 className="text-2xl font-bold">
              Unleash the Ultimate Showdown
            </h3>
            <div className="text-lg">
              Input the names of two characters and ignite an epic battle as our
              AI narrates their clash in vivid detail!
            </div>
          </div>
          <CharacterForm
            setResponse={setResponse}
            setIsLoading={setIsLoading}
            setError={setError} // Pass setError as a prop
          />
          {isLoading ? (
            <ClipLoader color={"#ffffff"} size={150} />
          ) : error ? ( // If there's an error, display it
            <div className="text-left text-4xl text-red-500">{error}</div>
          ) : response ? (
            <StoryFormatter
              text={response.story}
              fighter1Name={response.fighter1Name}
              fighter2Name={response.fighter2Name}
            />
          ) : null}
        </div>
      </main>
    </>
  );
};

export default Home;